# Generated by Django 4.2.9 on 2026-04-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season_end',
            field=models.DateField(blank=True, help_text='When this product goes out of season', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='season_start',
            field=models.DateField(blank=True, help_text='When this product comes into season', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='season_status',
            field=models.CharField(choices=[('in_season', 'In Season'), ('out_of_season', 'Out of Season'), ('coming_soon', 'Coming Soon')], default='in season', max_length=20),
        ),
    ]
