# Generated by Django 4.2.9 on 2026-04-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_product_season_end_product_season_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season_status',
            field=models.CharField(blank=True, choices=[('in_season', 'In Season'), ('out_of_season', 'Out of Season'), ('coming_soon', 'Coming Soon')], default='in season', max_length=20),
        ),
    ]
